[package]
edition = "2021"
name = "maze"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]
name = "maze"

[dependencies]
image = "0.24.7"
imageproc = "0.23.0"
pyo3 = "0.20.1"
rayon = "1.8.0"
