name: CI

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  linux-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
        target: [x86_64, x86, aarch64, armv7, s390x, ppc64le]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Build wheel (py-${{ matrix.python-version }})
        uses: PyO3/maturin-action@v1
        with:
          target: ${{ matrix.target }}
          args: --release --strip --out dist --interpreter python${{ matrix.python-version }}
          sccache: "true"
          manylinux: auto
      - name: Upload wheel (py-${{ matrix.python-version }})
        uses: actions/upload-artifact@v4
        with:
          name: wheel-${{ matrix.python-version }}
          path: dist

  release:
    runs-on: ubuntu-latest
    needs: linux-build
    steps:
      - name: Download wheels
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true
          path: dist
      - name: Create release
        id: release
        uses: ncipollo/release-action@v1
        with:
          tag: maze
          name: "maze"
          commit: main
          makeLatest: true
          allowUpdates: true
          removeArtifacts: true
          artifacts: dist/*.whl
      - name: Release URL
        run: |
          echo "Release URL: ${{ steps.release.outputs.html_url }}"

  sdist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build sdist
        uses: PyO3/maturin-action@v1
        with:
          command: sdist
          args: --out dist
      - name: Upload sdist
        uses: actions/upload-artifact@v4
        with:
          name: sdist
          path: dist
